### ISSUE TITLE
[JTC] Cleanup TODO-List from #320

### ISSUE THREAD

**Issue by christophfroehlich** [ros-controls/ros2_controllers#944]
To keep track of TODOs mentioned with #320:

- [ ] try minimizing the amount of includes #943
- [ ] check if this is needed at all https://github.com/ros-controls/ros2_controllers/blob/4c6d7236245c527f275b1e03a7e5242b658dc782/joint_trajectory_controller/include/joint_trajectory_controller/joint_trajectory_controller.hpp#L53-L61
- [x] clean the mess of trajectory msg pointers
- [x] rename `read_state_from_hardware` 
- [ ] try refactoring these into trajectory_operations.cpp or into trajectory.hpp directly https://github.com/ros-controls/ros2_controllers/blob/4c6d7236245c527f275b1e03a7e5242b658dc782/joint_trajectory_controller/include/joint_trajectory_controller/joint_trajectory_controller.hpp#L224-L241
- [ ] turn `compute_error_for_joint` into a proper function & unit test
- [ ] if "RealtimeSubscriber" existed with an API to check for new message & get message that'd make this very readable https://github.com/ros-controls/ros2_controllers/blob/4c6d7236245c527f275b1e03a7e5242b658dc782/joint_trajectory_controller/src/joint_trajectory_controller.cpp#L164-L165
- [ ] Convert `assign_interface_from_point` into member function

**Comment by christophfroehlich** [comment]
@bmagyar regarding 

> try refactoring these into trajectory_operations.cpp or into trajectory.hpp directly 

The methods

- `fill_partial_goal`
- `sort_to_local_joint_order`
- `validate_trajectory_msg`
- `add_new_trajectory_msg`

all use class variables, like `dof_`, `params_.joints` and so on. You suppose to refactor that without relying on class variables but add them as function parameters?
